### ISSUE TITLE
UNICODE and ANSI Errors

### ISSUE THREAD

**Issue by benyanke** [benyanke/GrandOrguePi#2]
(received in my inbox from a non-GH user)

> I managed to compile GO myself about a year ago and I’m now looking to compile a newer version when I came upon your script which would greatly simplify the process as I seem to recall having a few problems last time.
> 
> I’ve got a fresh install of the latest Raspbian Jessie, the version with the Pixel desktop however your script gets as far as CMAKE which then fails after trying with UNICODE and ANSI.
>

**Comment by watje999** [comment]
GRANDORGUE INSTALLER FOR RASPBERRY PI                                                                                                                 This has been tested on the Pi3                                                                                                                       running a clean Raspian Jesse install (03-18-2016 build).                                                                                             For more information, visit:                                                                                                                          https://github.com/benyanke/GrandOrguePi                                                                                                              ########################                                                                                                                              [] Updating package repository                                                                                                                        [] Getting most recent version of source code from github.                                                                                            [] Installing needed packages.                                                                                                                        [] Upgrading needed packages.                                                                                                                         [] Prepping with cmake for compiling.                                                                                                                       Cmake failed. Trying with ansi instead of unicode.
      Cmake prep failed. GrandOrgue could not be installed.

same problem here, on a Raspberry 3 model B+ . (It runs Aeolus perfectly.)

**Comment by benyanke** [comment]
I'm not really doing maintenance on this anymore, as I haven't been using GrandOrgue lately. However, if you're willing to debug and PR, I'd be happy to accept!

**Comment by djbottrill** [comment]
I have an modified version of the script that I’ve used on a PI 3 and a Tinkerboard it’s simply a matter of getting the dependencies correct.
All I did was manually run the compile command and when it failed I figured out what was missing.
I don’t have 3B yet so I can’t test it.

**Comment by benyanke** [comment]
Excellent, I'd love to keep this working if you're willing to get it going!

**Comment by djbottrill** [comment]
I've tested my updated version of the script on the latest version of Raspbian. Do you want me to upload to this thread or put it in my GitHub repository ?

**Comment by watje999** [comment]
I would like to try the new script very much indeed, can you mail it so I can do a test?

kind regards, Rene
klingeren@hotmail.com

**Comment by benyanke** [comment]
@djbottrill I'd encourage you to make a pull request (how github handles contributions from non-owners of a repository) by editing the file here to make your changes:

https://github.com/benyanke/GrandOrguePi/edit/master/installGoAuto.sh#edit

**Comment by neilwilson123** [comment]
I have GrandOrgue running great on my Mac and am trying to get it to run on a Raspberry Pi 4.
Get as far as ansi/unicode message as above when script bombs.
The Mac version works very well with our church organ as keyboards and amp (tone gen in organ is dead)
Pi could be a nice low cost solution to fix the problem (Mac or PC is a bit too expensive)
I there a working build or script available? It would be a great help.
Thanks Neil (Gower, South Wales)

**Comment by benyanke** [comment]
I haven't used grandorgue in years, so I wouldn't be in a position to support this. I should probably update the readme that this is abandoned.

However, feel free to use this as a starting point and fork it if you'd like!

**Comment by djbottrill** [comment]
I have a patched version that works I will upload in the morning and send a link.

GrandOrgue works quite well on a 4GB RPI 4 just needs good cooking.

David

**Comment by neilwilson123** [comment]
Many thanks David.
I look forward to giving it a try

Neil

**Comment by djbottrill** [comment]
Neil,

I have forked Ben’s version and have added the updates I’ve been using recently, my forked repository is here:

https://github.com/djbottrill/GrandOrguePi <https://github.com/djbottrill/GrandOrguePi>

Let me know how you get on.

If you are interested I’ve been developing keyboard scanner boards that use optical key switches, up to 16 Illuminated Pistons and provision for up to 4 swell / analogue control inputs per keyboard. The master Scanner board uses IPMIdi to send Midi messages over an Ethernet network to GrandOrgue or Hauptwerk.

I have an IPMidi example sketch for  Arduino boards also on my GitHub:

https://github.com/djbottrill/IPMidi_example <https://github.com/djbottrill/IPMidi_example>

 

David

**Comment by neilwilson123** [comment]
Thanks David, will try this out this evening (UK)

If all goes well I would be interested in your other developments. As a retired electronics graduate who has spent most of my working life in software and networking I may be able to assist.

Neil

**Comment by djbottrill** [comment]
Ditto :)

**Comment by neilwilson123** [comment]
I just had a few minutes to try the script but still get the same Cmake problem - see below

Any suggestions ?

Neil
 


GRANDORGUE INSTALLER FOR RASPBERRY PI

This has been tested on the Pi3
running a clean Raspian Jesse install (03-18-2016 build).

For more information, visit:
https://github.com/benyanke/GrandOrguePi

########################

[] Updating package repository
[] Getting most recent version of source code from github.
[] Installing needed packages.
[] Upgrading needed packages.
[] Prepping with cmake for compiling.
      Cmake failed. Trying with ansi instead of unicode.
      Cmake prep failed. GrandOrgue could not be installed.
pi@raspberrypi:~/NewGO $

**Comment by djbottrill** [comment]
Did you download the script from my github or use the wget command ?

You need to download my version and run through sudo.

David

**Comment by neilwilson123** [comment]
yes I got script from your github and ran with sudo.

cmake error log reads as follows.

Determining if the function snd_seq_client_info_get_card exists failed with the following output:
Change Dir: /home/pi/Newgo2/goBuild/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ad9b3/fast"
/usr/bin/make -f CMakeFiles/cmTC_ad9b3.dir/build.make CMakeFiles/cmTC_ad9b3.dir/build
make[1]: Entering directory '/home/pi/Newgo2/goBuild/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ad9b3.dir/CheckFunctionExists.c.o
/usr/bin/cc   -Wall -O3 -g -fomit-frame-pointer -funroll-loops -ffast-math -DCHECK_FUNCTION_EXISTS=snd_seq_client_info_get_card   -o CMakeFiles/cmTC_ad9b3.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_ad9b3
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ad9b3.dir/link.txt --verbose=1
/usr/bin/cc  -Wall -O3 -g -fomit-frame-pointer -funroll-loops -ffast-math -DCHECK_FUNCTION_EXISTS=snd_seq_client_info_get_card    -rdynamic CMakeFiles/cmTC_ad9b3.dir/CheckFunctionExists.c.o  -o cmTC_ad9b3 -lasound 
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_ad9b3.dir/build.make:87: cmTC_ad9b3] Error 1
make[1]: Leaving directory '/home/pi/Newgo2/goBuild/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_ad9b3/fast] Error 2

**Comment by djbottrill** [comment]
I’ll have a look tomorrow with the latest Raspbian it’s probably a dependancy issue.

David

**Comment by djbottrill** [comment]
Neil,

I’ve tested the script today and it installed without a problem.

I took the following steps:

Downloaded Raspbian Buster September 2019 
Used Etcher to copy to a Micro SD card
Once Raspbian had booted I allow it to do an online update
Download the script from https://github.com/djbottrill/GrandOrguePi <https://github.com/djbottrill/GrandOrguePi>
unzip the script  to /home/pi/
to install type:  sudo ./InstallGoAuto.sh 

I just let the installer run through it probably took about 45 minutes on my Raspberry Pi 4.

You will either need to log out and log in again or reboot for GrandOrgue to appear in the Sound & Video menu.


David

**Comment by benyanke** [comment]
Just updated the project readme to note the archival and link to https://github.com/djbottrill/GrandOrguePi.

Closing out and archiving this repo, I'd encourage you to continue work there. Best of luck!
